"""Allow NULL for komentar

Revision ID: 146f87673a73
Revises: a34c5be17a17
Create Date: 2024-12-06 03:21:29.784388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '146f87673a73'
down_revision = 'a34c5be17a17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peminjaman', schema=None) as batch_op:
        batch_op.alter_column('komentar',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peminjaman', schema=None) as batch_op:
        batch_op.alter_column('komentar',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
