"""null for komentar and string

Revision ID: 247ca0351421
Revises: fd22c0646503
Create Date: 2024-12-06 04:11:10.449634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '247ca0351421'
down_revision = 'fd22c0646503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peminjaman', schema=None) as batch_op:
        batch_op.alter_column('komentar',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peminjaman', schema=None) as batch_op:
        batch_op.alter_column('komentar',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
