"""Add komentar ditolak to Peminjaman

Revision ID: 6d33c43a1805
Revises: 37cd4ff1cbdd
Create Date: 2024-12-06 02:53:05.249550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d33c43a1805'
down_revision = '37cd4ff1cbdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peminjaman', schema=None) as batch_op:
        batch_op.add_column(sa.Column('komentar', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peminjaman', schema=None) as batch_op:
        batch_op.drop_column('komentar')

    # ### end Alembic commands ###
