"""Update status column to enum values

Revision ID: 86a186c22308
Revises: 36b3dc777041
Create Date: 2024-12-15 19:50:11.798391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86a186c22308'
down_revision = '36b3dc777041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('izin_kegiatan', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending', 'disetujui', 'ditolak', 'disposisi', 'selesai'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('izin_kegiatan', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending', 'disetujui', 'ditolak', 'disposisi', 'selesai'),
               nullable=False)

    # ### end Alembic commands ###
