"""Set default komentar

Revision ID: a34c5be17a17
Revises: e7808e1d1eaa
Create Date: 2024-12-06 03:15:12.742126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a34c5be17a17'
down_revision = 'e7808e1d1eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peminjaman', schema=None) as batch_op:
        batch_op.alter_column('komentar',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peminjaman', schema=None) as batch_op:
        batch_op.alter_column('komentar',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
