"""Add komentar ditolak to Peminjaman

Revision ID: e7808e1d1eaa
Revises: 6d33c43a1805
Create Date: 2024-12-06 03:06:35.158780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7808e1d1eaa'
down_revision = '6d33c43a1805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peminjaman', schema=None) as batch_op:
        batch_op.alter_column('komentar',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peminjaman', schema=None) as batch_op:
        batch_op.alter_column('komentar',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
